-- Shared question-quality feedback for aaronholmes.dev
-- Run this in the Supabase SQL editor for the project used by the site.

create table if not exists public.question_feedback (
    id bigint generated by default as identity primary key,
    client_id uuid not null,
    question_id text not null,
    reason text not null default 'bare',
    topic text,
    mastery_concept text,
    learning_objective text,
    learning_stage text,
    first_flagged_at timestamptz not null default now(),
    last_flagged_at timestamptz not null default now(),
    constraint question_feedback_reason_check check (
        reason in (
            'bare',
            'wording-gives-away-answer',
            'distractors-unrealistic',
            'answer-too-obvious',
            'possibly-incorrect',
            'explanation-unclear',
            'other'
        )
    ),
    constraint question_feedback_client_question_reason_unique
        unique (client_id, question_id, reason)
);

alter table public.question_feedback enable row level security;

-- Anonymous site visitors may submit question-quality signals.
create policy "allow anonymous feedback inserts"
on public.question_feedback
for insert
to anon
with check (true);

-- The public client may read only the non-sensitive rows used to build aggregate
-- counts. No free-text learner notes are stored in this table.
create policy "allow anonymous aggregate source reads"
on public.question_feedback
for select
to anon
using (true);

-- Upsert requires update permission when the same browser flags the same
-- question/reason again.
create policy "allow anonymous feedback updates"
on public.question_feedback
for update
to anon
using (true)
with check (true);

grant select, insert, update on public.question_feedback to anon;
grant usage, select on sequence public.question_feedback_id_seq to anon;
