-- Shared question-quality feedback for aaronholmes.dev
-- Run this in the Supabase SQL editor for the project used by the site.

create table if not exists public.question_feedback (
    id bigint generated by default as identity primary key,
    client_id uuid not null,
    question_id text not null,
    question_version integer not null default 1,
    semantic_key text,
    reason text not null default 'bare',
    topic text,
    mastery_concept text,
    learning_objective text,
    learning_stage text,
    first_flagged_at timestamptz not null default now(),
    last_flagged_at timestamptz not null default now(),
    constraint question_feedback_reason_check check (
        reason in (
            'bare',
            'wording-gives-away-answer',
            'distractors-unrealistic',
            'answer-too-obvious',
            'possibly-incorrect',
            'explanation-unclear',
            'other'
        )
    )
);

-- Migrations for projects created before question versioning / semantic grouping.
alter table public.question_feedback
    add column if not exists question_version integer not null default 1;

alter table public.question_feedback
    add column if not exists semantic_key text;

alter table public.question_feedback
    drop constraint if exists question_feedback_client_question_reason_unique;

create unique index if not exists question_feedback_client_question_version_reason_unique
    on public.question_feedback (client_id, question_id, question_version, reason);

-- semantic_key is intentionally not unique. It groups related question variants
-- while exact identity remains question_id + question_version. A later vector
-- embedding layer can discover broader semantic similarity without changing the
-- audit trail or merging distinct questions.
create index if not exists question_feedback_semantic_key_idx
    on public.question_feedback (semantic_key)
    where semantic_key is not null;

alter table public.question_feedback enable row level security;

-- Anonymous site visitors may submit question-quality signals.
drop policy if exists "allow anonymous feedback inserts" on public.question_feedback;
create policy "allow anonymous feedback inserts"
on public.question_feedback
for insert
to anon
with check (true);

-- The public client may read only the non-sensitive rows used to build aggregate
-- counts. No free-text learner notes are stored in this table.
drop policy if exists "allow anonymous aggregate source reads" on public.question_feedback;
create policy "allow anonymous aggregate source reads"
on public.question_feedback
for select
to anon
using (true);

-- Upsert requires update permission when the same browser flags the same
-- question/version/reason again.
drop policy if exists "allow anonymous feedback updates" on public.question_feedback;
create policy "allow anonymous feedback updates"
on public.question_feedback
for update
to anon
using (true)
with check (true);

-- Reversible flagging needs delete permission. The client issues a narrowly
-- filtered delete for its own generated client_id + question/version/reason.
-- client_id is anonymous browser state, not an account identifier.
drop policy if exists "allow anonymous feedback deletes" on public.question_feedback;
create policy "allow anonymous feedback deletes"
on public.question_feedback
for delete
to anon
using (true);

grant select, insert, update, delete on public.question_feedback to anon;
grant usage, select on sequence public.question_feedback_id_seq to anon;
